yet another pipeline fix

diff --git a/.github/workflows/git-commit-rules.yaml b/.github/workflows/git-commit-rules.yaml
--- a/.github/workflows/git-commit-rules.yaml
+++ b/.github/workflows/git-commit-rules.yaml
@@ -1,8 +1,12 @@
 name: Git Commit Rules
 
 on:
-  pull_request:
-    types: [opened, edited, synchronize, reopened]
+pull_request:
+  types:
+    - opened
+    - synchronize
+    - ready_for_review
+    - reopened
 
 jobs:
   commit-message-check:
@@ -11,18 +15,6 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
-      - name: Validate Commit Messages
-        run: |
-          pattern="^(fix|feat|pipeline|doc|wip)\(#TYP-[0-9]+\): .+|Merge .+"
-          for commit in $(git rev-list ${{ github.event.before }}..${{ github.event.after }}); do
-            message=$(git log --format=%B -n 1 $commit)
-            if ! [[ "$message" =~ $pattern ]]; then
-              echo "❌ Commit '$commit' is not formatted correctly."
-              echo "Allowed: fix|feat|pipeline|doc|wip(#TICKET-ID): Description"
-              echo "Did you run the setup.sh script?"
-              exit 1
-            fi
-          done
   pull-request-title:
     runs-on: ubuntu-latest
     needs: commit-message-check
@@ -30,10 +22,11 @@ jobs:
       - name: Validate PR Title
         if: env.ACT != 'true'
         run: |
-            pattern="^(fix|feat|pipeline|doc|wip)\(#TYP-[0-9]+\): .+"
-            pr_title="${{ github.event.pull_request.title }}"
-            if ! [[ "$pr_title" =~ $pattern ]]; then
-                echo "❌ Pull Request title is invalid!"
-                echo "Allowed format: fix|feat|pipeline|doc|wip(#TICKET-ID): Description"
-                exit 1
-            fi
+          pattern="^(fix|feat|pipeline|doc|wip)\(#TYP-[0-9]+\): .+"
+          pr_title="${{ github.event.pull_request.title }}"
+          if ! [[ "$pr_title" =~ $pattern ]]; then
+              echo "❌ Pull Request title is invalid!"
+              echo "Allowed format: fix|feat|pipeline|doc|wip(#TICKET-ID): Description"
+              exit 1
+          fi
+
